services:
  emby:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
    volumes:
      - "${DATA_PATH}:/config"
      - "${MOUNT_PATH}:/mnt/media"
    environment:
      - UID=1000
      - GID=1000
      - GIDLIST=1000,0
      - TZ=Asia/Shanghai
      - NASTOOL_AUTO_UPDATE=false  # 如需在启动容器时自动升级程程序请设置为true
      - NASTOOL_CN_UPDATE=false # 如果开启了容器启动自动升级程序，并且网络不太友好时，可以设置为true，会使用国内源进行软件更新
    image: hsuyelin/nas-tools:latest
    labels:  
      createdBy: "Apps"
networks:  
  1panel-network:  
    external: true
